[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

eyre = "*"
itertools = "*"
indoc = { version = "2.0.4", features = [] }
num = { version = "0.4.1", features = [] }
